In [2]:
import numpy as np
import matplotlib.pyplot as plt

# Arrays indexieren

Wir können auf Elemente eines Numpy Arrays ebenso wie in Python-Listen (oder Arrays aus anderen Programmiersprachen) per Index zugreifen. Auf das letzte Element können wir mit -1 zugreifen, wie wir das auch von Python-Listen gewohnt sind.

## Indizieren von eindimensionalen Arrays

In [3]:
M = np.array([1, 2, 3, 4])


## Indizieren von zweidimensionalen Arrays (Matrizen)
Um ein Elment in einer Matrix zu indizieren, können wir mit dem Format `row,column` arbeiten.

In [5]:
M = np.diag([1, 2, 3])


## Integer array indexing
Wir können beim Indexing auch einen Array mit Index-Positionen angeben

In [6]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Element in Zeile 1 und Spalte 3 indizieren (klassisch)


# 1 Zeile und dritte Zeile mit Array Indexing


# 1 Zeile und dritte Zeile mit Array Indexing


## Aufgabe

- Erstelle eine 2 x 3 Matrix M.
- Gebe den Shape des Arrays aus.
- Gebe den Wert in der zweiten Zeile und der ersten Spalte aus
- Gebe den Datentyp des Arrays aus

$ M = \left( \begin{matrix} 1 & 12 & 13 \\ 42 & 51 & 62 \end{matrix} \right) $

In [7]:
# Aufgabe: 5 Minuten Zeit

# Arrays Slicing (Ausschneiden von Werten aus Arrays)
Generell erzeugen Slicing Operationen in Numpy keinen neuen Array, sondern bieten einen sogenannten View auf das Ursprungsarray. verändert man die geslicte Submenge, verändert man auch die Originaldaten. Verhindern kann man das mit copy (siehe weiter unten).

## von eindimensionalen Arrays (Vektoren)
Eindimensionale Arrays lassen sich wie in Python mit dem Slicing-Operator sclicen. Schema `Start:End:Schrittweite`.

In [8]:
x = np.array([1, 2, 3, 4, 5, 6])


## von zweidimensionalen Arrays (Matritzen)
Zweidimensionale Arrays lassen sich wie in Python mit dem Slicing-Operator sclicen. 
Schema `Zeile von:Zeile bis, Spalte von:Spalte bis`.

$ M = \left( \begin{matrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{matrix} \right) $

In [10]:
M = np.array([[1, 2, 3], [4, 5, 6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

### alle Zeilen, die ersten beiden Spalten 

Um eine Matrix nach folgendem Schema aus M "auszuschneiden"
$ M = \left( \begin{matrix} 1 & 2 \\ 4 & 5 \end{matrix} \right) $

In [11]:
M = np.array([[1, 2, 3], [4, 5, 6]])
# alle Zeilen, die ersten beiden Spalten
...

array([[1, 2],
       [4, 5]])

### ersten zwei Zeilen, erste Spalte

In [12]:
M = np.array([[1, 2, 3], [4, 5, 6]])
#  (Slicing der ersten beiden Zeilen, Indexing der Spalte 0)
...

array([1, 4])

### alle Zeilen und die erste und dritte Spalte mit Multiindexing

In [10]:
M = np.array([[1, 2, 3], [4, 5, 6]])
# alle Zeilen und die erste und dritte Spalte mit Multiindexing
...

Ellipsis

### Diagonale aus zweidimensionalem Array

In [11]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Diagonale
...

Ellipsis

## Aufgabe
$X =  \left(  \begin{array}{rrrr} 
2 & 3 & 8 \\ 
1 & 22 & 22 \\ 
4 & 22 & 22 \\ 
\end{array} \right) $

a) Erstelle das zweidimensionale Array   
b) Schneide den Block mit den 22 aus (2 x 2 Matrix)    
c) Schneide die diagonalen Werte aus (als Vektor mit shape(3,) [2, 22, 22])

In [13]:
# Happy Coding: 5 Minuten Zeit
...

## copy
Um eine tatsächliche Kopie durch Slicing von einem Array zu erstellen, muss man die Methode Copy nutzen

In [14]:
# ohne copy: Verändern von Index 0 bei P_copy verändert auch P
...

In [15]:
# mit copy: Z bleibt unverändert
...