# Numpy Datentypen
Numpy Arrays bestehen immer aus Elementen eines Datentyps. Übersteigt ein Element des Arrays den Wert des eigentlichen Datentyps, kommt es oft zu unvorhergesehenen Effekten, die man nur verstehen kann, wenn man ein Verständnis von Datentypen im Allgemeinen und insbesondere den C-Datentypen hat. Die Datentypen von Numpy entsprechen den echten C-Datentypen.

Ist zum Beispiel der Datentyp eines Arrays uint8, ist der erlaubte Wertebereich der Elemente von 0 bis 255 (8 Bit). Negative Werte oder Werte, die 255 übersteigen, lassen sich mit uint8 einfach nicht abbilden. Trägt man nun trotzdem zum Beispiel ein Element mit Wert 256 ein, wird in der Ausgabe der Wert 0 ausgegeben. Warum?

Gucken wir uns das mal auf Binärebene an. Das ist die Zahl 256 als Binärzahl:
100000000
Beim Abzählen sehen wir, dass die Zahl 9 Stellen hat, also 9 Bit. Diese Zahl passt nicht in das 8 Bit-Format und daraus folgt, dass folgende Zahl in den Speicher gelegt wird.
00000000. Die 1 am Anfang wurde also einfach abgeschnitten.

Das ist die Binärzahl für 0. Deshalb sehen wir in der Ausgabe 0 (siehe Biespiel unten). Die Binärzahl für 257 ist übrigens 100000001. Man sollte sich denken können, welche Zahl man in der Ausgabe sieht. Neuere Versionen von Numpy warnen vor dem Überlauf und lassen diese Operationen nicht zu.


## Den richtigen Datentyp wählen
Generell sollte man darauf achten, den richtigen Datentyp zu wählen. Immer int64 zu wählen ist allerdings ebensowenig richtig, weil das viel Speicherplatz verschwendet. 
Der Datentyp kann entweder als String angegeben werden oder als np-Konstante

In [2]:
import numpy as np
x = np.array([1, 2, 3], dtype="float64")
y = np.array([3, 4, 5], dtype=np.float64)
x, y

(array([1., 2., 3.]), array([3., 4., 5.]))


## Vorzeichenbehaftete Integer
int8, int16, int32, int64

int8 hat zum Beispiel den Wertebereich -128 to 127.    
int32 hat zum Beispiel den Wertebereich -2147483648 to 2147483647   
int64 hat den Wertebereich -9223372036854775808 to 9223372036854775807   

## Vorzeichenlose Integer
uint8 hat zum Beispiel den Wertebereich 0 - 255.    
uint32 hat zum Beispiel den Wertebereich 0 - 4294967295       
uint64 hat den Wertebereich 0 - $2^{64}-1$

## Fließkommazahlen
float32 
und float64 


In [10]:
data = np.random.randint(1, 10, (8, 2)).astype(np.float32)
data


array([[4., 8.],
       [2., 7.],
       [9., 1.],
       [5., 7.],
       [6., 9.],
       [3., 7.],
       [8., 9.],
       [5., 1.]], dtype=float32)

In [11]:
import numpy as np

# es wurden Elemente in die Liste gegeben, die nicht dem gewählten Datentyp uint8 entsprechen.
x = np.array([255, 256, 257], dtype="uint8")
x

OverflowError: Python integer 256 out of bounds for uint8

## bestehendes Array in anderen Datentyp umwandeln mit astype
Es ist einfach, ein bestehendes Array in einen anderen Datentyp zumzuwandeln. Dazu wählt man die Methode `astype`.

In [12]:
# unsigned int16 Vektor in int32 umwandeln

array([255, 256, 257], dtype=int32)

## Datentyp für Unicode Strings
Obwohl Numpy für numerische Operationen gedacht ist, stehen auch Datentypen für Unicode-Strings zur Verfügung. Ein String mit der Länge 6 (abcdef) hat zum Beispiel den Datentyp <U6.

In [1]:
# Array mit Strings

## Rundung
Numpy nutzt das gleich Rundungsverfahren wie Python's built-in Funktion round: das mathematische Runden (ROUND_HALF_TO_EVEN)

### Mathematisches Runden (ROUND_HALF_TO_EVEN)

In [2]:
# normalverteilte 3 x 4 Matrix mit Pseudozufallszahlen

auf 3 Dezimalstellen gerundet

In [4]:
# auf 3 Nachkommastellen runden

Alternativ geht auch folgendes:

In [20]:
# Runden über die round-Methode des ndarray-Objekts

array([[-0.25, -2.06,  1.22, -2.89],
       [-0.59, -1.34,  0.37, -0.4 ],
       [-0.5 , -0.47, -0.15,  0.64]])

### kaufmännisches Runden
Um kaufmännisches Runden zu implementieren, was selten nötig ist, muss man sich eine Befehlfsfunktion schreiben

In [5]:
def round_half_up(n, decimals=0):
    multiplier = 10**decimals
    return np.floor(n * multiplier + 0.5) / multiplier

