# Numpy uFuncs - Universelle Funktionen

Auf Numpy-Arrays können mit Numpy Universellen Funktionen elementweise Operationen in  hoher Geschwindigkeit ausgeführt werden. Der Grund ist, dass die Operationen vektorisiert werden, d.h. durch die CPU spezialiserte, parallele Abarbeitung von Operationen stattfindet (SIMD, Single Instruction, Multiple Data). 

Siehe auch: https://de.wikipedia.org/wiki/Flynnsche_Klassifikation

## Simple arithmetische Operatoren
Arithmetische Operatoren sind in Numpy als uFunctions implementiert und operieren auf allen Elementen.

In [1]:
import numpy as np

a = np.array([1, 1])
b = np.array([2, 3])

# Basic operations

# oder mit Operatoren


## Skalarmultiplikation

 Dabei wird jeder Eintrag des Vektors mit dem Skalar (in diesem Fall 5) multipliziert.

In [6]:
z = np.array([1, 2, 3])
y = np.array([[1, 2, 3], [3, 4, 5]])
# Multiplizieren aller Werte von z und y mit dem Skalar 5

z, y

(array([1, 2, 3]),
 array([[1, 2, 3],
        [3, 4, 5]]))

### quadratische gleichung in Numpy implementiert
$f(x) = -2x^2 + 3$    
$f: \mathbb{R} → \mathbb{R}$    
(Definitionsbereich: Menge der reelen Zahlen, Wertebereich: Menge der reelen Zahlen)


1. **Elementweise Potenzierung**: Jedes Element des Vektors \(x\) wird quadriert (\(x^2\)).
2. **Skalarmultiplikation**: Das quadrierte Ergebnis wird mit \(-2\) multipliziert, wodurch die Werte skaliert und negativiert werden (\(-2x^2\)).
3. **Addition eines Skalars**: Zum Ergebnis wird der Skalar \(3\) addiert, wodurch die Funktion um \(3\) auf der y-Achse verschoben wird.

In [8]:
# Aufgabe: quadratische Gleichung schreiben

In [9]:
# mit Linspace ein Intervall zwischen -20 und 20 erstellen und Plotten
# und Funktion plotten

## Elemente eines Arrays durch einen Wert teilen

In [10]:
# Division

## Zwei mehrdimensionale Arrays elementweise multiplizieren
eine normale Multiplikation ist keine Matrix-Multiplikation, sondern eine elementweise Multiplikation. Hier ist darauf zu achten, dass die Shapes der beiden Arrays übereinstimmen.

$ A = \left( \begin{matrix} 2 & 3 \\ 4 & 5 \end{matrix} \right) $
$ B = \left( \begin{matrix} 1 & 2 \\ 3 & 4 \end{matrix} \right) $
$ C = \left( \begin{matrix} 2 & 6 \\ 12 & 20 \end{matrix} \right) $

In [7]:
A = np.array([[2, 3], [4, 5]])
B = np.array([[1, 2], [3, 4]])
C = A * B
C

array([[ 2,  6],
       [12, 20]])

## Matrixmultiplikation

### Regel der Matrix-Multiplikation

Die Matrix-Multiplikation ist definiert, wenn die **Anzahl der Spalten der ersten Matrix** gleich der **Anzahl der Zeilen der zweiten Matrix** ist.

#### Mathematische Regel:
Wenn \( A \) eine Matrix der Dimension \( m \times n \) ist und \( B \) eine Matrix der Dimension \( n \times p \), dann ist das Produkt \( C = A \cdot B \) eine Matrix der Dimension \( m \times p \).

#### Berechnung eines Eintrags:
Der Eintrag \( c_{ij} \) in der \(i\)-ten Zeile und \(j\)-ten Spalte der Matrix \(C\) wird berechnet als:
\[
c_{ij} = \sum_{k=1}^n a_{ik} \cdot b_{kj}
\]
Dabei wird das **Skalarprodukt** der \(i\)-ten Zeile von \(A\) mit der \(j\)-ten Spalte von \(B\) gebildet.

---

### Beispiel:
Sei $ A $ eine $2 \times 3$-Matrix:
$$
A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix}
$$

und $ B $ eine $3 \times 2$-Matrix:

$$
B = \begin{pmatrix} 7 & 8 \\ 9 & 10 \\ 11 & 12 \end{pmatrix}
$$


Dann ist das Produkt $ C = A \cdot B $ eine $2 \times 2$-Matrix:
$$
C = \begin{pmatrix} (1\cdot7 + 2\cdot9 + 3\cdot11) & (1\cdot8 + 2\cdot10 + 3\cdot12) \\ (4\cdot7 + 5\cdot9 + 6\cdot11) & (4\cdot8 + 5\cdot10 + 6\cdot12) \end{pmatrix}
$$

$$
C = \begin{pmatrix} 58 & 64 \\ 139 & 154 \end{pmatrix}
$$

---

### Hinweise:
1. Die Matrix-Multiplikation ist **nicht kommutativ**: $ A \cdot B \neq B \cdot A $ (in der Regel).
2. Die Matrix-Multiplikation ist **assoziativ**: $ (A \cdot B) \cdot C = A \cdot (B \cdot C) $.
3. Die Matrix-Multiplikation ist **distributiv**: $ A \cdot (B + C) = A \cdot B + A \cdot C $.

$ A = \left( \begin{matrix} 2 & 3 & 4 \\ 4 & 5 & 1 \end{matrix} \right) $
$ B = \left( \begin{matrix} 1 & 2 \\ 3 & 4 \\ 2 & 4 \end{matrix} \right) $
$ C = \left( \begin{matrix} 19 & 32 \\ 21 & 32 \end{matrix} \right) $

In [13]:
A = np.array([[2, 3, 4], [4, 5, 1]])
B = np.array([[1, 2], [3, 4], [2, 4]])
C = A @ B
print(A)
print("--")
print(B)
print("--")
print(C)
C = B @ A
print(C)

[[2 3 4]
 [4 5 1]]
--
[[1 2]
 [3 4]
 [2 4]]
--
[[19 32]
 [21 32]]
[[10 13  6]
 [22 29 16]
 [20 26 12]]


## Absolute Werte der Elemente einer Matrix mit abs

In [9]:
x = np.random.normal(loc=1, scale=5, size=10)
absolute_values = np.abs(x)
absolute_values

array([1.71331339, 5.45842897, 1.72092464, 7.25323411, 6.02620421,
       6.09216099, 5.85655394, 6.08106993, 0.53579987, 3.5138726 ])

## Größter gemeinsamer Teiler

In [10]:
A = np.array([[2, 6], [4, 8]])
B = np.array([[1, 9], [3, 16]])
print(A)
print(B)
np.gcd(A, B)

[[2 6]
 [4 8]]
[[ 1  9]
 [ 3 16]]


array([[1, 3],
       [1, 8]])

## kleinstes gemeinsames Vielfaches

In [11]:
A = np.array([[2, 6], [4, 8]])
B = np.array([[1, 9], [3, 16]])
print(A)
print(B)
np.lcm(A, B)

[[2 6]
 [4 8]]
[[ 1  9]
 [ 3 16]]


array([[ 2, 18],
       [12, 16]])

## Modulo

In [12]:

A = np.array([[2, 6], [4, 8]])
B = np.array([[1, 9], [3, 16]])
print(A)
print(B)
A % B

[[2 6]
 [4 8]]
[[ 1  9]
 [ 3 16]]


array([[0, 6],
       [1, 8]])

## Arithmetische Vergleichsfunktionen

Arithmetische Vergleichsfunktionen in NumPy ermöglichen elementweise Vergleiche zwischen Arrays oder zwischen einem Array und einem Skalar. Beispiele sind **größer** \((>)\), **kleiner gleich** \((\leq)\), oder **gleich** \((==)\), die jeweils ein Boolesches Array zurückgeben. Neben den Funktionen wie `np.greater(a, b)` oder `np.equal(a, b)` kann auch die **Operatorenschreibweise** direkt verwendet werden, z. B. `a > b` oder `a == b`, da NumPy diese Operatoren überlädt und äquivalent ausführt.


In [14]:
A = np.array([[2, 6], [4, 8]])
B = np.array([[1, 9], [3, 16]])

A < B

array([[False,  True],
       [False,  True]])

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [15]:
A = np.array([[2, 6], [4, 8]])
B = np.array([[1, 9], [3, 16]])

A >= B, A != B

(array([[ True, False],
        [ True, False]]),
 array([[ True,  True],
        [ True,  True]]))

## Trigonometrische Funktionen

In [13]:
theta = np.linspace(0, 2 * np.pi, 10)
sine = np.sin(theta)
cos = np.cos(theta)
sine, cos

(array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
         3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
        -6.42787610e-01, -2.44929360e-16]),
 array([ 1.        ,  0.76604444,  0.17364818, -0.5       , -0.93969262,
        -0.93969262, -0.5       ,  0.17364818,  0.76604444,  1.        ]))

# Aufgabe: Gewichtete Features berechnen

### Beschreibung:
In Machine Learning werden Feature-Matrizen oft mit Gewichten skaliert, um die Bedeutung einzelner Features zu verändern. Du hast eine Feature-Matrix und eine Gewichtsmatrix, und du sollst die gewichtete Feature-Matrix berechnen, indem du die beiden Matrizen elementweise multiplizierst.

In [11]:
import numpy as np

# Feature-Matrix (z.B. 3 Samples mit 4 Features)
features = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# Gewichtsmatrix (jedes Feature hat ein Gewicht)
weights = np.array([[0.5, 1.0, 1.5, 2.0]])

# TODO: Berechne die gewichtete Feature-Matrix
weighted_features = ...

print("Original Feature-Matrix:")
print(features)

print("\nGewichtsmatrix:")
print(weights)

print("\nGewichtete Feature-Matrix:")
print(weighted_features)


Original Feature-Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Gewichtsmatrix:
[[0.5 1.  1.5 2. ]]

Gewichtete Feature-Matrix:
Ellipsis


## erwartete Ausgabe

Original Feature-Matrix:

[    
[ 1  2  3  4]    
 [ 5  6  7  8]    
 [ 9 10 11 12]    
]   

Gewichtsmatrix:

[[0.5 1.  1.5 2. ]]

Gewichtete Feature-Matrix:

[[ 0.5  2.   4.5  8. ]    
 [ 2.5  6.   10.5 16. ]    
 [ 4.5 10.  16.5 24. ]]    
