# Broadcasting
Broadcasting in NumPy ermöglicht arithmetische Operationen zwischen Arrays unterschiedlicher Formen, indem kleinere Arrays automatisch an größere angepasst werden. Eine Dimension mit 1 wird entsprechend "gestreckt", um die Operation zu ermöglichen. Dadurch spart NumPy Speicher und Rechenzeit, ohne unnötige Kopien der Daten zu erstellen.

![title](broadcasting_1.png)

In [2]:
import numpy as np

In [6]:
a = np.array([1, 2, 3])
b = np.array([2])

result = a * b
result

x = a * 2
print(x)
print(result)

[2 4 6]
[2 4 6]


## 1) Arrays mit unterschiedlichem Shape addieren
Arrays können miteinander addiert werden, wenn sie a) den gleichen Shape haben oder b) einer der Shapes 1 ist.

In [1]:
...

Ellipsis

## 2) Skalar-Multiplikation
Skalar zu Array-Broadcasting: Der Skalar wird auf die gesamte Form des Arrays erweitert.

$a = 3$

$ M = \left( \begin{matrix} 4 & 2 \\ 3 & 5 \\ 2 & 9 \end{matrix} \right) \cdot a = \left( \begin{matrix} 12 & 6 \\ 9 & 15 \\ 6 & 27 \end{matrix} \right) $

In [2]:
M = np.array([[4, 2], [3, 5], [2, 9]])
M * 3

Ellipsis

## Übungsaufgabe: Temperaturumrechnung für mehrere Städte

Gegeben sind die die Tagesdurchschnittstemperaturen (in °C) für mehrere Städte über eine Woche in einem 2D-Array vorliegen. Deine Aufgabe ist es, diese Temperaturen mithilfe von Broadcasting in Fahrenheit umzurechnen.

In [3]:
import numpy as np

# Temperaturen in Grad Celsius für 4 Städte über 7 Tage
temperatures_celsius = np.array([
    [15, 17, 20, 21, 19, 18, 16],  # Stadt 1
    [10, 12, 15, 14, 13, 11, 9],   # Stadt 2
    [25, 27, 28, 29, 30, 26, 24],  # Stadt 3
    [5, 7, 10, 12, 8, 6, 4]        # Stadt 4
])

# TODO: Konvertiere die Temperaturen in Fahrenheit
# Formel: Fahrenheit = Celsius * 9/5 + 32



### Erwartete Ausgabe

Temperaturen in Fahrenheit:

[[59.   62.6  68.   69.8  66.2  64.4  60.8]   
 [50.   53.6  59.   57.2  55.4  51.8  48.2]     
 [77.   80.6  82.4  84.2  86.   78.8  75.2]     
 [41.   44.6  50.   53.6  46.4  42.8  39.2]]    
